### ISSUE TITLE
SSL更新できない問題

### ISSUE THREAD

**Issue by ghost** [disco-v8/DirectEdit#1]
このスクリプトを取得してSSL取得を行ったところ、
PHPエラーが発生しました。

↓エラーメッセージです。

Error output from txtregist.php:
PHP Warning:  file_get_contents(https://www.mydns.jp/directedit.html): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden 7
 in txtregist.php on line 75

Error output from txtregist.php:
PHP Warning:  file_get_contents(https://www.mydns.jp/directedit.html): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden 7
 in txtregist.php on line 75

```
Waiting for verification...
Cleaning up challenges
Error output from txtdelete.php:
PHP Warning:  file_get_contents(https://www.mydns.jp/directedit.html): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden 7
 in txtdelete.php on line 75

Error output from txtdelete.php:
PHP Warning:  file_get_contents(https://www.mydns.jp/directedit.html): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden 7
 in txtdelete.php on line 75
```

Failed authorization procedure. hogehoge.0am.jp (dns-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: No TXT record found at _acme-challenge.hogehoge.0am.jp

なお、パスワード、ドメインなどは正しく設定しました。

**Comment by disco-v8** [comment]
ご質問いただきました件ですが、週末のサーバー構築ハンズオンでも一部生徒さんで同様の症状が発生しました。
設定はすべて合っていたのですが、念のため？と思って再度GitHubからダウンロード＆展開し直して設定し直したら、同じコマンドなのにサーバー証明書の取得まで問題ありませんでした。
最初のファイル全てと二回目を比較すれば何か差異が見つかったかもしれませんが、ハンズオン中でしたのでそこまで調べることができませんでした。

なので、もう一度ダウンロード＆展開し直して設定し直してお試しいただくといかがでしょうか？

よろしくご確認ください。

**Comment by EmmanuelChanel** [comment]
私も同じトラブルで Let's Encrypt の証明書を取得できませんでした。 GitHub からダウンロードし直して設定し直しても駄目でした。(今、 Let's Encrypt から何度も失敗しているからと、登録停止だかを食らっています。)

**Comment by EmmanuelChanel** [comment]
環境の問題なのでしょうか？私の環境は Ubuntu Server 18.04 LTS で php は 7.2 です。

**Comment by disco-v8** [comment]
その後いかがでしょうか？
タイミングによりできないことがあるみたいなので、自分の場合には毎月3,13,23日とかに更新をトライするようにしていますが。
情報お待ちしております。

**Comment by EmmanuelChanel** [comment]
あきらめて手動で証明書を取得しました。さっきこれを試してみてもこんな状態です。
$ sudo ./txtregist.php
PHP Warning:  file_get_contents(https://www.mydns.jp/directedit.html): failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden 6

**Comment by disco-v8** [comment]
そのように実行しても、そのようなエラーが出て正常です。
このスクリプトは単独では動作しません。

このスクリプトは、READMEに書いてあるようにcertbotコマンドのオプションの一つとして指定するためのものですので。

具体的にご利用されているドメイン名と、何月何日の何時何分頃にcertbotコマンドを実行したのかを、別途MyDNS.JPのCONTACT USからご連絡いただければ、より詳しく調査がてきます。
よろしくご検討ください。

**Comment by ghost** [comment]
私の環境はRaspbian (Debian 9.4)です。PHP等はすべてインストール済みです。
結論としては、Certbotのほうを使用して自作スクリプトを組んで更新しています。

**Comment by disco-v8** [comment]
どうもタイミングでエラーになることがあるようです。
このスクリプト自体で完結していればいいのですが、certbotから呼ばれるものなので、エラーになったら少し時間をおいてから再度トライしてね、というエラーメッセージを出すくらいしかできないかも、ですが、そのあたり時間を見て手を加えたいと思います。

**Comment by yasunohara** [comment]
disco-v8さん：
私の環境でも同じようにForbiddenエラーが出ます(環境: Ubuntu 18.04LTS Server/PHP 7.2)。証明書の更新なので、設定に間違いはないはずです。
エラーの詳細を取得するため、$POST_OPTIONSに
`'ignore_errors' => TRUE`
という設定を追加したところ、403のエラーコードとともに

> DNSINFO is not correct.

というbodyが届いていることが分かりました。
ご参考になりますでしょうか？

**Comment by disco-v8** [comment]
yasunoharaさん、めちゃくちゃ参考になる情報ありがとうございます。
サーバーのログを見てみましたら、確かに"DNSINFO is not correct"というのがyasunoharaさんのIDというかドメインで発生していました。
ただ、原因が特定できていませんので、ちょっと究明のための仕込みなどをさせてください。
出来ましたらこちら(とメール)でご連絡させていただきますので、再度お試しいただければと思います。

少しお待ちください。

**Comment by disco-v8** [comment]
yasunoharaさん、より詳細に"DNSINFO is not correct"の理由が表示＆記録できるように準備ができましたので、お試しいただければと思います。
こちらでも原因が判明次第、改修をしたいと思います。

**Comment by disco-v8** [comment]
…(EmmanuelChanelさんとyasunoharaさんは別問題っぽい？ので、そのパターンももう少し詳しいエラーを出すように仕込みをしてみました)

**Comment by yasunohara** [comment]
disco-v8さん
早速の対応ありがとうございます。再度試してみたところ、

> DNSINFO is not correct.
> Characters of the Content is illegal.(CAA)

という、より詳細なエラーメッセージが返ってくるようになりました。

先日、CAAレコードを設定したのを思い出し、MyDNS.jpのAdministratorページから

> Hostname: ＠
Type: CAA
Content: 0 issuewild "letsencrypt.org"

という設定を削除してみたところ、無事通りました！
Contentにスペースが入っていたのが原因のように思います。

ありがとうございました。

**Comment by disco-v8** [comment]
無事解決したようでよかったです…というか、いや、スペースが入っていてもOKでないといけないので、それについてはこれから調べてみます。

**Comment by disco-v8** [comment]
判りました、CAAレコードを設定されている方のみ、"の扱いがバグっていたので、正しく更新できていませんでした。
CAAレコードを設定されていても正しく更新されるようになりました。
(ただしいCAAレコード設定でないと、エラーになります)

ご指摘ご協力ありがとうございました!!

**Comment by Rei-Nanao** [comment]
こちらのissue、閉じないのでしょうか……？
解決したのかしてないのかいまいちわからず、使用すべきか判断しかねたので……。

**Comment by disco-v8** [comment]
その後ですが、その後のハンズオンでは問題ないので、やはりタイミングの問題かと思われます。
が、私としては「何もしていない」ので…どうしましょ？いったん閉じておきますかね。

**Comment by EmmanuelChanel** [comment]
私は閉じて構いません。今回試行してみて成功しました。
今回間違っていたのはスクリプトの位置で、前も間違っていたなどという事もあるのかも知れませんが、実際の原因ではないと叫びたくなる感じだったりします。ともあれ、今回成功できてよかったです。
この ISSUE のために、いろいろ動作確認してくださり、ありがとうございました。
