### ISSUE TITLE
SSL更新できない問題 2024

### ISSUE THREAD

**Issue by EmmanuelChanel** [disco-v8/DirectEdit#3]
この前は自然解決した感じだったのですが、今回、 emmanuelchanel.com と emmanuelc.dix.asia の Let's Encrypt でのSSL更新が出来ません。
ここのスクリプトが動いているかも不明なのですが、私がその他に使っている、更新時期がきていない utsunomiya-lrt.com と u-lrt.0am.jp がシミュレーションをパスするようで、どうして動かないのかさっぱり分からない感じです。
ワイルドカードは1つまでしか使えないとか、そういう制約でもあるのでしょうか？
---- ログ ----
# certbot renew
Saving debug log to /var/log/letsencrypt/letsencrypt.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/emmanuelc.dix.asia.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Renewing an existing certificate for emmanuelc.dix.asia and 2 more domains

Certbot failed to authenticate some domains (authenticator: manual). The Certificate Authority reported these problems:
  Domain: users.emmanuelc.dix.asia
  Type:   unauthorized
  Detail: Incorrect TXT record "v=spf1 +ip4:222.10.24.64 a:auth.gate-on.net a mx include:_spf.emmanuelc.dix.asia -all" found at _acme-challenge.users.emmanuelc.dix.asia

Hint: The Certificate Authority failed to verify the DNS TXT records created by the --manual-auth-hook. Ensure that this hook is functioning correctly and that it waits a sufficient duration of time for DNS propagation. Refer to "certbot --help manual" and the Certbot User Guide.

Failed to renew certificate emmanuelc.dix.asia with error: Some challenges have failed.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/emmanuelc.f5.si.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not yet due for renewal

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/emmanuelchanel.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Renewing an existing certificate for emmanuelchanel.com and 3 more domains

Certbot failed to authenticate some domains (authenticator: manual). The Certificate Authority reported these problems:
  Domain: users.emmanuelchanel.com
  Type:   unauthorized
  Detail: Incorrect TXT record "google-site-verification=c_ZieKDIjC7mAFIo-ML6o_aGvYW6DMEbzlxP-nKSq_A" (and 1 more) found at _acme-challenge.users.emmanuelchanel.com

  Domain: wiki.emmanuelchanel.com
  Type:   unauthorized
  Detail: Incorrect TXT record "google-site-verification=c_ZieKDIjC7mAFIo-ML6o_aGvYW6DMEbzlxP-nKSq_A" (and 1 more) found at _acme-challenge.wiki.emmanuelchanel.com

Hint: The Certificate Authority failed to verify the DNS TXT records created by the --manual-auth-hook. Ensure that this hook is functioning correctly and that it waits a sufficient duration of time for DNS propagation. Refer to "certbot --help manual" and the Certbot User Guide.

Failed to renew certificate emmanuelchanel.com with error: Some challenges have failed.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/u-lrt.0am.jp.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not yet due for renewal

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/utsunomiya-lrt.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Certificate not yet due for renewal

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
The following certificates are not due for renewal yet:
  /etc/letsencrypt/live/emmanuelc.f5.si/fullchain.pem expires on 2024-03-27 (skipped)
  /etc/letsencrypt/live/u-lrt.0am.jp/fullchain.pem expires on 2024-03-26 (skipped)
  /etc/letsencrypt/live/utsunomiya-lrt.com/fullchain.pem expires on 2024-03-26 (skipped)
All renewals failed. The following certificates could not be renewed:
  /etc/letsencrypt/live/emmanuelc.dix.asia/fullchain.pem (failure)
  /etc/letsencrypt/live/emmanuelchanel.com/fullchain.pem (failure)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
2 renew failure(s), 0 parse failure(s)
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

**Comment by EmmanuelChanel** [comment]
Certbot では、ACMEチャレンジが、最後のワイルドカードつきドメイン名についてするものなのに、 DirectEdit では、メインのドメイン名にワイルドカードをつけたものである事が前提で稼働しているために、機能していなかったのか知らん？という感じです。
*.emmanuelchanel.com と *.emmanuelc.dix.asia それぞれの設定を最後に持っていくと、自動更新(certbot renew --force-renew )が機能したようでした。

**Comment by disco-v8** [comment]
具体的にどのようなコマンドを打たれているのかが判らないので何ともですが、ワイルドカード証明書？としているなら、「users.emmanuelc.dix.asia」というホスト名を設定しているが、それは「*.emmanuelc.dix.asia」に含まれているぞ？、ということではないでしょうか？

**Comment by EmmanuelChanel** [comment]
自動更新出来なくて試してみたコマンドは、以下のような感じです。
-d (メインドメイン名),(その他サブドメイン名),(ワイルドカード付きメインドメイン名) の順に記述しないと機能しない。
と認識して、入力しました。
-----
certbot certonly --force-renew --manual \
--preferred-challenges=dns \
--manual-auth-hook /var/www/letsencrypt/emmanuelchanel.com/txtregist.php \
--manual-cleanup-hook /var/www/letsencrypt/emmanuelchanel.com/txtdelete.php \
**-d 'emmanuelchanel.com,*.users.emmanuelchanel.com,*.wiki.emmanuelchanel.com,*.emmanuelchanel.com'** \
--server https://acme-v02.api.letsencrypt.org/directory \
--agree-tos -m emmanuelchanel@gmail.com \
--manual-public-ip-logging-ok

certbot certonly --force-renew --manual \
--preferred-challenges=dns \
--manual-auth-hook /var/www/letsencrypt/emmanuelc.dix.asia/txtregist.php \
--manual-cleanup-hook /var/www/letsencrypt/emmanuelc.dix.asia/txtdelete.php \
**-d 'emmanuelc.dix.asia,*.users.emmanuelc.dix.asia,*.emmanuelc.dix.asia'** \
--server https://acme-v02.api.letsencrypt.org/directory \
--agree-tos -m emmanuelchanel@gmail.com \
--manual-public-ip-logging-ok
----
certbot renew --force-renew で一度成功したので、これが解決策だと思ったのですが、 certbot renew --dry-run では失敗を弾き出したので、思い違いか知らん？と思ったりしているところです。
>具体的にどのようなコマンドを打たれているのかが判らないので何ともですが、ワイルドカード証明書？としているなら、「users.emmanuelc.dix.asia」というホスト名を設定しているが、それは「*.emmanuelc.dix.asia」に含まれているぞ？、ということではないでしょうか？
それで、 users.emmanuelc.dix.asia は含まず、 emmanuelc.dix.asia と *.emmanuelc.dix.asia と *.users.emmanuelc.dix.asia を指定しています。 ワイルドカードは、1つレベルが下のサブドメイン名にだけ全ての文字列で、全てのレベルではないというのがSSL証明書のようです。

**Comment by disco-v8** [comment]
ああ、まさに『「users.emmanuelc.dix.asia」というホスト名を設定しているが、それは「*.emmanuelc.dix.asia」に含まれているぞ？』ですね。

> -d 'emmanuelchanel.com,.users.emmanuelchanel.com,.wiki.emmanuelchanel.com,*.emmanuelchanel.com'

とされていますが、「*.emmanuelc.dix.asia」には「users.emmanuelchanel.com」も「wiki.emmanuelchanel.com」も含まれており、含まれていないのは最初の「emmanuelchanel.com」だけなので、証明書に記名してもらうホスト名としては

 -d 'emmanuelchanel.com, *.emmanuelchanel.com'

これだけが正解だと思います。

ちなみに私はこのような-d '～, ～, ～, ～'という方式ではやらずに、

 -d emmanuelchanel.com -d *.emmanuelchanel.com

というように、いちいち「-d」を記名して欲しいホスト名として指定しています。

よろしくご確認ください。

**Comment by EmmanuelChanel** [comment]
すみません、ここの記法をよく知らないで書いたので、私が書こうとした事が正常に表示されていません。
.users.emmanuelchanel.com と .wiki.emmanuelchanel.com の文字の前には、 * の文字列がついています。
phpBB のコードタグでもあれば、いいのですが、それがなくて、ここに書けない感じです。
実際は以下のような感じです。
https://pastebin.com/iw7G05Tp
仰る、いちいち -d (ホスト名) と書く形式もやってみます。

**Comment by EmmanuelChanel** [comment]
いちいち -d (ホスト名) と書く形式のコマンドも成功しました。
https://pastebin.com/kDycj9PM
強制更新も成功しました。
https://pastebin.com/jGpm0TY4
certbot renew --dry-run
は失敗します。

**Comment by disco-v8** [comment]
もしかして「emmanuelc.dix.asia」と「*.emmanuelchanel.com」という指定の他に
「*.users.emmanuelc.dix.asia」というワイルドカード証明書が欲しい、ということでしょうか？

でしたら「users.emmanuelc.dix.asia」というサブドメインとして(MyDNS.JPなら)子IDに移譲(DELEGATE)して、
その子IDで「users.emmanuelc.dix.asia」と「*.users.emmanuelc.dix.asia」について、別途certbotしないといけないと思います。

よろしくご確認ください。

**Comment by EmmanuelChanel** [comment]
あの、

**Comment by EmmanuelChanel** [comment]
あの、すみません、こちらとしては、自己解決(もどき？)した報告の積もりで書きました。
子IDを作ったほうが確実なのでしょうが、気まぐれなどで後で変更する事も考えていて、ちょっとそこまではする気になれない次第です。このやり方で出来そうと判断して、自動更新の時期を待ってみたいところです。
後、これ以上は自動更新スクリプトの範囲ではなくて、 certbot の利用者に報告すべき範囲なのかも知れません。

**Comment by disco-v8** [comment]
了解です。
こちらの認識としては、DirectEdit、というよりはcertbotの使い方が間違えているという旨のご指摘でした。
また何かございましたらお気軽にご連絡ご質問ください。
