### ISSUE TITLE
txtregist.phpでTXTレコードが更新されない

### ISSUE THREAD

**Issue by takevox** [disco-v8/DirectEdit#4]
証明書発行の為利用させていただいていますが、
READMEの通りに進めても、DNS-01が通りません。
debug.logを見ると、CERTBOT_DOMAINとCERTBOT＿VALIDATIONはリクエストに含まれているようですが
TXTレコードが更新されないようです。

debug.logの内容てきには、更新時に返ってくるはずのレスポンスではなく、ホームページのHTMLが帰ってきているように思われます。

念のため、/txtedit.confに設定した内容と、debug.logで取得したCERTBOT_DOMAIN/CERTBOT_VALIDATIONの値をPostmanで投げたところ200となった場合は更新されたり、307となって成功したりと安定しません。

こちらのスクリプトを利用するうえで何か設定の見直しや注意点があれば教えてください。

debug.log
```
CERTBOT_DOMAIN=weelworks.com
CERTBOT_VALIDATION=YgfnPyEaX8pEuSfShmOpTWPxDUWhS8FN1nq0_wxHsVU
CERTBOT_TOKEN=FALSE
CERTBOT_CERT_PATH=FALSE
CERTBOT_KEY_PATH=FALSE
CERTBOT_SNI_DOMAIN=FALSE
CERTBOT_AUTH_OUTPUT=FALSE
EDIT_CMD=REGIST
MYDNSJP_QUERY=CERTBOT_DOMAIN=weelworks.com&CERTBOT_VALIDATION=YgfnPyEaX8pEuSfShmOpTWPxDUWhS8FN1nq0_wxHsVU&CERTBOT_TOKEN=0&CERTBOT_CERT_PATH=0&CERTBOT_KEY_PATH=0&CERTBOT_SNI_DOMAIN=0&CERTBOT_AUTH_OUTPUT=0&EDIT_CMD=REGIST
MYDNSJP_CONTENTS=<!DOCTYPE html>
<html lang="en" dir="ltr" class="no-js">

        <!-- Header -->
        <head>

<!-- ==============================================
Title and basic Metas
=============================================== -->
```

**Comment by testtlnls** [comment]
私もtakevoxさんと同様の状況と思われます．（私が確認した限りは307 Temporary Redirectしか観測できませんでした）
私の場合は以前に取得していた証明書を同じ手順で更新しようとしたところでした．

最後の成功時(10/28)から設定は変えていないはずです．（LetsEncryptと違い，ZeroSSLなのでドメイン検証は毎回必要）

画像は以下のHTMLによるGoogle Chrome DevToolsスクリーンショットです．

```
<form method="POST" target="a">
<input name="CERTBOT_DOMAIN">
<input name="CERTBOT_VALIDATION">
<input name="EDIT_CMD" value="REGIST">
<input type="submit" value="submit">
</form>
```

![20241116-mydnsdedit](https://github.com/user-attachments/assets/014f4936-f4d1-4c28-adb6-ebb2d72ee151)

**Comment by disco-v8** [comment]
情報ありがとうございます。
先日VPSを変更しましたので、そこで何か設定が漏れた可能性があります。
少しお時間をいただければと思います。

**Comment by disco-v8** [comment]
いろいろと調査をしましたところ、MyDNS.JPが動いているサーバーを入れ替えた際に、PHPのエラー判定の設定が厳しくなっていたため、今まではWARNINGで済んでいたところがERRORとなって、処理が途中で止まっていました。

処理をきちんと記述して、問題なく処理が進むことを確認しました。

ご迷惑をおかけしまして、申し訳ございませんでした。

**Comment by takevox** [comment]
調査と対応ありがとうございました。

証明書の更新も無事完了できることを確認できました。
